### ISSUE TITLE
Preview images before clone

### ISSUE THREAD

**Issue by wkurosawa** [caepenna/meme-responses#1]
Is there a way to preview images as list here in github, instead of visualizing one by one?

I want to check if this response is already here (which I believe is not)

![foi mal tava doidao](https://pbs.twimg.com/media/Ccp26TrWEAYkjkw.jpg)

**Comment by caepenna** [comment]
![10011495_818526334843985_488660997_n](https://cloud.githubusercontent.com/assets/2954723/20845702/79bdbb0a-b8ad-11e6-8dc0-1d344d8e44d2.jpg)

Well, I can't say I have a solution for that. Any suggestions would be welcome :)

You could maybe download the repository… that can help.
